spring:
  application:
    name: ams-backend

  datasource:
    url: jdbc:mysql://localhost:3307/bluemoon_ams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: NhapMonCongNghePhanMem
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: bmoonamin@gmail.com
    password: Nhomittn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret-key: BlueMoonAMS2026SecretKeyForJWTTokenGenerationDoNotUseInProduction
    expiration-ms: 86400000
  google:
    # Thay bằng Client ID thật từ Google Cloud Console
    # Dạng: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
    client-id: 553757322807-spvpjrtctpntbt6onovneqptc3l5p919.apps.googleusercontent.com
  upload:
    proof-dir: uploads/proofs
    cccd-dir: uploads/cccd
    chat-dir: uploads/chat
