spring:
  application:
    name: ams-backend

  datasource:
    url: jdbc:mysql://localhost:3307/bluemoon_ams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: NhapMonCongNghePhanMem
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: bmoonamin@gmail.com
    password: rpoo dmer aban slae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret-key: BlueMoonAMS2026SecretKeyForJWTTokenGenerationDoNotUseInProduction
    expiration-ms: 86400000


